### ISSUE TITLE
Simplification: Use the AWS Cloud Control API

### ISSUE THREAD

**Issue by robmoss2k** [cloudgraphdev/cloudgraph-provider-aws#1]
Although several (generally older) services do not support the [Cloud Control API](https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/what-is-cloudcontrolapi.html), the newer ones tend to do so. Implementing this would extend the supported services to most of AWS without having to write per-service implementations. Please see the [list of supported resource types](https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html).

**Comment by tyler-dunkel** [comment]
@robmoss2k Really sorry for taking so long to get back to you. We have looked into the cloud control API and believe it is still a little too new to rely on. We have a plan to give it another look early next year. Thanks for the help!
