### ISSUE TITLE
SNS scan only returns first page of results

### ISSUE THREAD

**Issue by dylanhanning** [cloudgraphdev/cloudgraph-provider-aws#56]
**Describe the bug**

When running `cg scan aws` for SNS topics, the CLI seems to correctly follow the page tokens and make multiple queries.

However, it only returns the first page of results to Cloudgraph. Since the maximum page size from the AWS API is 100, it means it will only ever save 100 SNS topics to Cloudgraph/Dgraph.

The output I get always looks like:

```
ℹ Printing scan report...
┌─────────┬─────────────────┬────────┐
│ Service │ Resources Found │ Status │
├─────────┼─────────────────┼────────┤
│ sns     │ 100             │ ✔      │
├─────────┼─────────────────┼────────┤
│ total   │ 100             │ N/A    │
└─────────┴─────────────────┴────────┘
```

Despite my AWS account containing more than 100 topics.

Also, for some reason the command only works with `CG_DEBUG=5` set. Without that flag, it always fails with:

```
✖ Unknown type "AddawsSnsInput".
✖ Unknown type "AddawsAccountInput".
✖ Unknown type "AddawsTagInput".
```

**To Reproduce**
1. Set `"resources": "sns"` in `.cloud-graphrc.json`.
1. Run `CG_DEBUG=5 cg scan aws`

**Expected behavior**
To return and save all SNS topics, even if the total count exceeds one page (i.e. 100 topics).

**Environment (please complete the following information):**
 - CLI version (installed via NPM): `@cloudgraph/cli/0.21.4 darwin-x64 node-v18.1.0`
 - Provider versions: `aws@0.80.0`.
 - Context: Local machine. MacOS 12.3.1.

**Additional context**

I think this might be caused by this line:
https://github.com/cloudgraphdev/cloudgraph-provider-aws/blob/main/src/services/sns/data.ts#L77-L81

I changed this locally to resolve _only if the nextToken is empty_ and that seemed to fix the issue (though it then fails later when fetching the subscriptions, so other changes may be needed):
```
if (nextToken) {
    listTopicArns(nextToken)
} else {
    resolve(topicArnList)
}
```

**Comment by tyler-dunkel** [comment]
Hi @dylanhanning wanted to let you know weve put in a fix for this issue and release it to our alpha branch. If you want to test it out in alpha you can do so by running `cg provider add aws@0.81.0-alpha.2` and then running `cg scan aws`. Thanks again for reporting this!

**Comment by dylanhanning** [comment]
Hi @m-pizarro @tyler-dunkel  thanks for the quick response.

I've done a quick test with `aws@0.81.0-alpha.2` and got the following error:

```
ℹ Fetching subscriptions for each topic...
⠋ SCANNING data for awsℹ Rate exceeded for SNS:sns:listSubscriptionsByTopic. Retrying...
.../lib/node_modules/@cloudgraph/cli/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error [TypeError]: Subscriptions is not iterable (cannot read property undefined)
    at Response.<anonymous> (.../lib/node_modules/@cloudgraph/cli/node_modules/@cloudgraph/cg-provider-aws/dist/services/sns/data.js:110:31)
```

**Comment by m-pizarro** [comment]
Hi @dylanhanning thanks for testing this,  we would really appreciate it. We will be reviewing it today. Sorry about this!

**Comment by tyler-dunkel** [comment]
@dylanhanning we just put in a fix for this and it should be releasing soon. if you install `aws@0.81.0-alpha.3` you will be able to try out the latest. Thanks again for reporting this!

**Comment by dylanhanning** [comment]
Hi @tyler-dunkel I've tried `aws@0.81.0-alpha.3` and got the following:

```
⠼ SCANNING data for awsSUBSCRIPTIONS: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] NextToken: undefined Data: [object Object]
⠧ SCANNING data for awsSUBSCRIPTIONS: undefined NextToken: undefined Data: null
/.../lib/node_modules/@cloudgraph/cli/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error [TypeError]: Subscriptions is not iterable (cannot read property undefined)
    at Response.<anonymous> (/.../lib/node_modules/@cloudgraph/cli/node_modules/@cloudgraph/cg-provider-aws/dist/services/sns/data.js:119:31)
```

`data` is null but it still tries to add it to the list of subscriptions. I think the issue [is here](https://github.com/cloudgraphdev/cloudgraph-provider-aws/blob/200c7f238c1b4f5142770e357ea4fc4a1e16d155/src/services/sns/data.ts#L87-L89) where it's missing a `return`? Adding that fixed it for me.

**Comment by tyler-dunkel** [comment]
@m-pizarro can you take a look at this when you get a chance? Thanks for your through testing @dylanhanning

**Comment by tyler-dunkel** [comment]
@dylanhanning This is ready for another test if you would be willing! Version is `0.81.0-alpha.5`

**Comment by dylanhanning** [comment]
Hi both, yes that seems to have fixed the issue. Thanks for looking into this!
